version: "3.8"
services:
  home: 
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/home
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./home
      dockerfile: Dockerfile-home
    container_name: home-container
    ports:
      - "3001:3001"
    depends_on:
      - header
      - chart1
      - sidenav
      - inputuser
      - showuser
      - store
  chart1: 
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/chart1
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./chart1
      dockerfile: Dockerfile-chart1
    container_name: chart1-container
    ports:
      - "3002:3002"
    depends_on:
      - store
  header:
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/header
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./header
      dockerfile: Dockerfile-header
    container_name: header-container
    ports:
      - "3004:3004"
    depends_on:
      - store
  inputuser: 
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/inputuser
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./inputuser
      dockerfile: Dockerfile-inputuser
    container_name: inputuser-container
    ports:
      - "3010:3010"
    depends_on:
      - store
  showuser: 
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/showuser
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./showuser
      dockerfile: Dockerfile-showuser
    container_name: showuser-container
    ports:
      - "3011:3011"
    depends_on:
      - store
  sidenav: 
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/sidenav
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./sidenav
      dockerfile: Dockerfile-sidenav
    container_name: sidenav-container
    ports:
      - "3005:3005"
  store:
    stdin_open: true
    tty: true
    image: reactpoccontainer.azurecr.io/store
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 2048M
            reservations:
              cpus: '0.25'
              memory: 1536M
    build:
      context: ./store
      dockerfile: Dockerfile-store
    container_name: store-container
    ports:
      - "3009:3009"
      

  